-- ==========================================
-- Faith Flow 資料庫初始化腳本
-- 自動從 faith_flow_sql.sql 清理生成
-- ==========================================

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

-- ==========================================
-- Functions (觸發器函數)
-- ==========================================

CREATE OR REPLACE FUNCTION update_comment_like_count() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        UPDATE community_comments 
        SET like_count = like_count + 1 
        WHERE comment_id = NEW.comment_id;
        RETURN NEW;
    ELSIF TG_OP = 'DELETE' THEN
        UPDATE community_comments 
        SET like_count = GREATEST(like_count - 1, 0) 
        WHERE comment_id = OLD.comment_id;
        RETURN OLD;
    END IF;
END;
$$;

-- ==========================================
-- Tables
-- ==========================================

-- AI Questions Table
CREATE TABLE ai_questions (
    ai_question_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_text character varying(255) NOT NULL,
    is_active boolean DEFAULT true NOT NULL
);

-- Card Styles Table
CREATE TABLE card_styles (
    card_style_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    style_name character varying(255),
    front_image_url text NOT NULL
);

-- Cards Unlock Table
CREATE TABLE cards_unlock (
    inlock_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    community_post_id bigint,
    letter_id bigint,
    comment_id bigint,
    CONSTRAINT chk_cards_unlock_target_at_least_one CHECK (
        (community_post_id IS NOT NULL) OR 
        (letter_id IS NOT NULL) OR 
        (comment_id IS NOT NULL)
    )
);

-- Collections Table
CREATE TABLE collections (
    collect_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    collection_name character varying(255),
    diary_cover_id bigint,
    created_at timestamp with time zone DEFAULT now()
);

-- Community Comment Likes Table
CREATE TABLE community_comment_likes (
    comment_id bigint NOT NULL,
    user_id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (comment_id, user_id)
);

-- Community Comments Table
CREATE TABLE community_comments (
    comment_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id bigint NOT NULL,
    user_id bigint NOT NULL,
    parent_comment_id bigint,
    comment_content text NOT NULL,
    like_count integer DEFAULT 0,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone
);

-- Community Post Likes Table
CREATE TABLE community_post_likes (
    post_id bigint NOT NULL,
    user_id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (post_id, user_id)
);

-- Community Post Shares Table
CREATE TABLE community_post_shares (
    share_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_post_id integer NOT NULL,
    shared_post_id integer,
    shared_by_user_id integer NOT NULL,
    share_caption text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp without time zone
);

-- Community Posts Table
CREATE TABLE community_posts (
    post_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_user_id bigint NOT NULL,
    letter_id bigint,
    diary_id bigint,
    post_content text,
    visibility character varying(50) DEFAULT 'public'::character varying NOT NULL,
    like_count integer DEFAULT 0,
    share_count integer DEFAULT 0,
    comment_count integer DEFAULT 0,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now(),
    deleted_at timestamp with time zone,
    CONSTRAINT chk_community_posts_content_source CHECK (
        (letter_id IS NOT NULL) OR 
        (diary_id IS NOT NULL) OR 
        (post_content IS NOT NULL)
    ),
    CONSTRAINT community_posts_visibility_check CHECK (
        (visibility)::text = ANY (ARRAY[
            ('public'::character varying)::text, 
            ('friends'::character varying)::text, 
            ('private'::character varying)::text
        ])
    )
);

-- Conversation Forks Table
CREATE TABLE conversation_forks (
    fork_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_conversation_id bigint,
    from_message_id bigint,
    from_message_version_id bigint,
    new_conversation_id bigint NOT NULL,
    forked_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Conversations Table
CREATE TABLE conversations (
    conversation_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    title character varying(255),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now(),
    deleted_at timestamp with time zone
);

-- Diary Table
CREATE TABLE diary (
    diary_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    collect_id integer,
    diary_content text NOT NULL,
    diary_cover_id bigint,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now(),
    deleted_at timestamp with time zone
);

-- Diary Covers Table
CREATE TABLE diary_covers (
    diary_cover_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cover_image_url text NOT NULL
);

-- Letters Table
CREATE TABLE letters (
    letter_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id bigint,
    card_style_id bigint NOT NULL,
    question_text text NOT NULL,
    answer_content text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Message Citation Table
CREATE TABLE message_citation (
    message_id bigint NOT NULL,
    citation jsonb
);

-- Message Versions Table
CREATE TABLE message_versions (
    message_version_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id bigint NOT NULL,
    version_number integer NOT NULL,
    message_content text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Messages Table
CREATE TABLE messages (
    message_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id bigint NOT NULL,
    parent_message_id bigint,
    sender character varying(50) NOT NULL,
    message_content text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT messages_sender_check CHECK (
        (sender)::text = ANY (ARRAY[
            ('user'::character varying)::text, 
            ('assistant'::character varying)::text
        ])
    )
);

-- Search Queries Table
CREATE TABLE search_queries (
    search_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    query_text text NOT NULL,
    searched_at timestamp with time zone DEFAULT now() NOT NULL
);

-- User Table
CREATE TABLE "user" (
    "userID" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username character varying(255) NOT NULL UNIQUE,
    email character varying(255) NOT NULL UNIQUE,
    password_hash character varying(255) NOT NULL,
    bio text,
    profile_picture_url text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now(),
    deleted_at timestamp with time zone
);

-- User Cards Table
CREATE TABLE user_cards (
    user_card_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    weekly_cards_id bigint NOT NULL,
    source_user_id bigint,
    obtained_at timestamp with time zone DEFAULT now() NOT NULL
);

-- User Draws Table
CREATE TABLE user_draws (
    draw_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    weekly_card_id bigint,
    drawn_at timestamp with time zone DEFAULT now() NOT NULL
);

-- User Follow Table
CREATE TABLE user_follow (
    follow_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    follower_user_id bigint NOT NULL,
    following_user_id bigint NOT NULL,
    followed_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT user_follow_no_self_follow CHECK (follower_user_id <> following_user_id),
    UNIQUE (follower_user_id, following_user_id)
);

-- Weekly Cards Table
CREATE TABLE weekly_cards (
    weekly_cards_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_style_id bigint NOT NULL,
    ai_question_id bigint NOT NULL,
    week_start_date date NOT NULL UNIQUE,
    week_end_date date NOT NULL
);

-- ==========================================
-- Indexes
-- ==========================================

CREATE INDEX idx_cards_unlock_comment ON cards_unlock(comment_id);
CREATE INDEX idx_cards_unlock_post ON cards_unlock(community_post_id);
CREATE INDEX idx_cards_unlock_user ON cards_unlock(user_id);
CREATE INDEX idx_collections_user ON collections(user_id);
CREATE INDEX idx_community_comment_likes_comment ON community_comment_likes(comment_id);
CREATE INDEX idx_community_comment_likes_user ON community_comment_likes(user_id);
CREATE INDEX idx_community_comments_parent ON community_comments(parent_comment_id);
CREATE INDEX idx_community_comments_post ON community_comments(post_id);
CREATE INDEX idx_community_comments_user ON community_comments(user_id);
CREATE INDEX idx_community_post_likes_post ON community_post_likes(post_id);
CREATE INDEX idx_community_post_likes_user ON community_post_likes(user_id);
CREATE INDEX idx_community_posts_author ON community_posts(author_user_id);
CREATE INDEX idx_community_posts_diary ON community_posts(diary_id);
CREATE INDEX idx_community_posts_letter ON community_posts(letter_id);
CREATE INDEX idx_conversation_forks_from_conversation ON conversation_forks(from_conversation_id);
CREATE INDEX idx_conversation_forks_new_conversation ON conversation_forks(new_conversation_id);
CREATE INDEX idx_conversations_user ON conversations(user_id);
CREATE INDEX idx_diary_collection ON diary(collect_id);
CREATE INDEX idx_diary_user ON diary(user_id);
CREATE INDEX idx_letters_card_style ON letters(card_style_id);
CREATE INDEX idx_letters_conversation ON letters(conversation_id);
CREATE INDEX idx_message_versions_message ON message_versions(message_id);
CREATE INDEX idx_messages_conversation ON messages(conversation_id);
CREATE INDEX idx_messages_parent ON messages(parent_message_id);
CREATE INDEX idx_search_queries_user ON search_queries(user_id);
CREATE INDEX idx_user_cards_user ON user_cards(user_id);
CREATE INDEX idx_user_cards_weekly ON user_cards(weekly_cards_id);
CREATE INDEX idx_user_draws_user ON user_draws(user_id);
CREATE INDEX idx_user_draws_weekly_card ON user_draws(weekly_card_id);
CREATE INDEX idx_user_follow_follower ON user_follow(follower_user_id);
CREATE INDEX idx_user_follow_following ON user_follow(following_user_id);
CREATE INDEX idx_weekly_cards_week ON weekly_cards(week_start_date);

-- ==========================================
-- Foreign Keys
-- ==========================================

-- Cards Unlock Foreign Keys
ALTER TABLE cards_unlock
    ADD CONSTRAINT fk_cards_unlock_comment 
    FOREIGN KEY (comment_id) REFERENCES community_comments(comment_id) ON DELETE CASCADE;

ALTER TABLE cards_unlock
    ADD CONSTRAINT fk_cards_unlock_post 
    FOREIGN KEY (community_post_id) REFERENCES community_posts(post_id) ON DELETE CASCADE;

ALTER TABLE cards_unlock
    ADD CONSTRAINT fk_cards_unlock_user 
    FOREIGN KEY (user_id) REFERENCES "user"("userID") ON DELETE CASCADE;

-- Collections Foreign Keys
ALTER TABLE collections
    ADD CONSTRAINT fk_collections_user 
    FOREIGN KEY (user_id) REFERENCES "user"("userID") ON DELETE CASCADE;

-- Community Comment Likes Foreign Keys
ALTER TABLE community_comment_likes
    ADD CONSTRAINT fk_comment_likes_comment 
    FOREIGN KEY (comment_id) REFERENCES community_comments(comment_id) ON DELETE CASCADE;

ALTER TABLE community_comment_likes
    ADD CONSTRAINT fk_comment_likes_user 
    FOREIGN KEY (user_id) REFERENCES "user"("userID") ON DELETE CASCADE;

-- Community Comments Foreign Keys
ALTER TABLE community_comments
    ADD CONSTRAINT fk_comments_parent 
    FOREIGN KEY (parent_comment_id) REFERENCES community_comments(comment_id) ON DELETE CASCADE;

ALTER TABLE community_comments
    ADD CONSTRAINT fk_comments_post 
    FOREIGN KEY (post_id) REFERENCES community_posts(post_id) ON DELETE CASCADE;

ALTER TABLE community_comments
    ADD CONSTRAINT fk_comments_user 
    FOREIGN KEY (user_id) REFERENCES "user"("userID") ON DELETE CASCADE;

-- Community Post Likes Foreign Keys
ALTER TABLE community_post_likes
    ADD CONSTRAINT fk_post_likes_post 
    FOREIGN KEY (post_id) REFERENCES community_posts(post_id) ON DELETE CASCADE;

ALTER TABLE community_post_likes
    ADD CONSTRAINT fk_post_likes_user 
    FOREIGN KEY (user_id) REFERENCES "user"("userID") ON DELETE CASCADE;

-- Community Posts Foreign Keys
ALTER TABLE community_posts
    ADD CONSTRAINT fk_community_posts_author 
    FOREIGN KEY (author_user_id) REFERENCES "user"("userID") ON DELETE CASCADE;

ALTER TABLE community_posts
    ADD CONSTRAINT fk_community_posts_letter 
    FOREIGN KEY (letter_id) REFERENCES letters(letter_id) ON DELETE SET NULL;

ALTER TABLE community_posts
    ADD CONSTRAINT fk_post_diary 
    FOREIGN KEY (diary_id) REFERENCES diary(diary_id) ON DELETE SET NULL;

-- Conversations Foreign Keys
ALTER TABLE conversations
    ADD CONSTRAINT fk_conversations_user 
    FOREIGN KEY (user_id) REFERENCES "user"("userID") ON DELETE CASCADE;

-- Conversation Forks Foreign Keys
ALTER TABLE conversation_forks
    ADD CONSTRAINT fk_forks_from_conversation 
    FOREIGN KEY (from_conversation_id) REFERENCES conversations(conversation_id) ON DELETE SET NULL;

ALTER TABLE conversation_forks
    ADD CONSTRAINT fk_forks_from_message 
    FOREIGN KEY (from_message_id) REFERENCES messages(message_id) ON DELETE CASCADE;

ALTER TABLE conversation_forks
    ADD CONSTRAINT fk_forks_from_message_version 
    FOREIGN KEY (from_message_version_id) REFERENCES message_versions(message_version_id) ON DELETE CASCADE;

ALTER TABLE conversation_forks
    ADD CONSTRAINT fk_forks_new_conversation 
    FOREIGN KEY (new_conversation_id) REFERENCES conversations(conversation_id) ON DELETE CASCADE;

-- Diary Foreign Keys
ALTER TABLE diary
    ADD CONSTRAINT fk_diary_collection 
    FOREIGN KEY (collect_id) REFERENCES collections(collect_id) ON DELETE CASCADE;

ALTER TABLE diary
    ADD CONSTRAINT fk_diary_user 
    FOREIGN KEY (user_id) REFERENCES "user"("userID") ON DELETE CASCADE;

-- Letters Foreign Keys
ALTER TABLE letters
    ADD CONSTRAINT fk_letters_card_style 
    FOREIGN KEY (card_style_id) REFERENCES card_styles(card_style_id) ON DELETE RESTRICT;

ALTER TABLE letters
    ADD CONSTRAINT fk_letters_conversation 
    FOREIGN KEY (conversation_id) REFERENCES conversations(conversation_id) ON DELETE SET NULL;

-- Message Citation Foreign Keys
ALTER TABLE message_citation
    ADD CONSTRAINT fk_message_citation_message 
    FOREIGN KEY (message_id) REFERENCES messages(message_id) ON DELETE CASCADE;

-- Message Versions Foreign Keys
ALTER TABLE message_versions
    ADD CONSTRAINT fk_message_versions_message 
    FOREIGN KEY (message_id) REFERENCES messages(message_id) ON DELETE CASCADE;

-- Messages Foreign Keys
ALTER TABLE messages
    ADD CONSTRAINT fk_messages_conversation 
    FOREIGN KEY (conversation_id) REFERENCES conversations(conversation_id) ON DELETE CASCADE;

ALTER TABLE messages
    ADD CONSTRAINT fk_messages_parent 
    FOREIGN KEY (parent_message_id) REFERENCES messages(message_id) ON DELETE SET NULL;

-- Search Queries Foreign Keys
ALTER TABLE search_queries
    ADD CONSTRAINT fk_search_queries_user 
    FOREIGN KEY (user_id) REFERENCES "user"("userID") ON DELETE CASCADE;

-- User Cards Foreign Keys
ALTER TABLE user_cards
    ADD CONSTRAINT fk_user_cards_source_user 
    FOREIGN KEY (source_user_id) REFERENCES "user"("userID") ON DELETE SET NULL;

ALTER TABLE user_cards
    ADD CONSTRAINT fk_user_cards_user 
    FOREIGN KEY (user_id) REFERENCES "user"("userID") ON DELETE CASCADE;

ALTER TABLE user_cards
    ADD CONSTRAINT fk_user_cards_weekly_cards 
    FOREIGN KEY (weekly_cards_id) REFERENCES weekly_cards(weekly_cards_id) ON DELETE RESTRICT;

-- User Draws Foreign Keys
ALTER TABLE user_draws
    ADD CONSTRAINT fk_user_draws_user 
    FOREIGN KEY (user_id) REFERENCES "user"("userID") ON DELETE CASCADE;

ALTER TABLE user_draws
    ADD CONSTRAINT fk_user_draws_weekly_card 
    FOREIGN KEY (weekly_card_id) REFERENCES weekly_cards(weekly_cards_id) ON DELETE SET NULL;

-- User Follow Foreign Keys
ALTER TABLE user_follow
    ADD CONSTRAINT fk_user_follow_follower 
    FOREIGN KEY (follower_user_id) REFERENCES "user"("userID") ON DELETE CASCADE;

ALTER TABLE user_follow
    ADD CONSTRAINT fk_user_follow_following 
    FOREIGN KEY (following_user_id) REFERENCES "user"("userID") ON DELETE CASCADE;

-- Weekly Cards Foreign Keys
ALTER TABLE weekly_cards
    ADD CONSTRAINT fk_weekly_cards_ai_question 
    FOREIGN KEY (ai_question_id) REFERENCES ai_questions(ai_question_id) ON DELETE RESTRICT;

ALTER TABLE weekly_cards
    ADD CONSTRAINT fk_weekly_cards_card_style 
    FOREIGN KEY (card_style_id) REFERENCES card_styles(card_style_id) ON DELETE RESTRICT;

-- ==========================================
-- Triggers
-- ==========================================

CREATE TRIGGER trg_update_comment_like_count
    AFTER INSERT OR DELETE ON community_comment_likes
    FOR EACH ROW
    EXECUTE FUNCTION update_comment_like_count();

-- ==========================================
-- 測試資料 (可選)
-- ==========================================

-- 插入測試用戶
INSERT INTO "user" (username, email, password_hash, profile_picture_url, bio, created_at) VALUES
('賴思嘉', 'lai.sijia@faithflow.com', '$2b$12$dummyhash1', 'https://lh3.googleusercontent.com/a/ACg8ocK6Arb6sfCv8o1ranOUNB06oKKQbiu4dGNaMGLnA1Ug7Hd0rgxu=s96-c', NULL, NOW()),
('Ting Kao', 'ting.kao@faithflow.com', '$2b$12$dummyhash2', 'https://lh3.googleusercontent.com/a/ACg8ocL6KqtwGvOp8pU60uzp8yuPbVdqPResSTXId4eZm6ZDKT-YS8B73Q=s96-c', NULL, NOW()),
('hahaha', 'hahaha@faithflow.com', '$2b$12$dummyhash3', 'https://lh3.googleusercontent.com/a/ACg8ocKue3oT7UyvFNSm7ji9rtVPIRzbdqhIX7Emh-T9uyaLZJoXUFg=s96-c', NULL, NOW()),
('旻翰', 'minhan@faithflow.com', '$2b$12$dummyhash4', 'https://lh3.googleusercontent.com/a/ACg8ocJiJr7MARQf1DqdR5e-ZXpUhOl_Ytja1RsWiI2UTm_LCzPoziv7=s96-c', NULL, NOW()),
('李欣頤', 'lee.xinyi@faithflow.com', '$2b$12$dummyhash5', 'https://lh3.googleusercontent.com/a/ACg8ocJeD529YuYGLxu3qipAAP4cgTOv8ku2oS_vKNVbRim1eCFd3XQn=s96-c', '', NOW()),
('時Iris', 'iris.shi@faithflow.com', '$2b$12$dummyhash6', 'https://lh3.googleusercontent.com/a/ACg8ocL7gFnKJsPyM8EKVk-ixIAcRPNEGay02TOhx5-TqeC_R7B3iXs=s96-c', '', NOW())
ON CONFLICT (email) DO NOTHING;

-- ==========================================
-- 完成訊息
-- ==========================================

DO $$
BEGIN
    RAISE NOTICE '✅ Faith Flow 資料庫初始化完成!';
    RAISE NOTICE '📊 已建立 % 個使用者', (SELECT COUNT(*) FROM "user");
    RAISE NOTICE '❓ 已建立 % 個 AI 問題', (SELECT COUNT(*) FROM ai_questions);
    RAISE NOTICE '🎨 已建立 % 個卡片樣式', (SELECT COUNT(*) FROM card_styles);
    RAISE NOTICE '';
    RAISE NOTICE '🚀 資料庫已準備就緒,可以開始使用!';
END $$;