-- 天主教禮儀日曆資料表
CREATE TABLE IF NOT EXISTS liturgical_calendar (
    liturgical_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    date TEXT NOT NULL UNIQUE,
    weekday TEXT NOT NULL,
    celebration TEXT NOT NULL,
    liturgical_rank TEXT NOT NULL,
    season TEXT NOT NULL,
    is_sunday BOOLEAN NOT NULL,
    is_holy_day BOOLEAN NOT NULL
);

-- 插入資料
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-01-01', 'Thu', '天主之母聖瑪利亞 (元旦)', '節日', '聖誕期', false,true);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-01-02', 'Fri', '聖誕期平日', '平日', '聖誕期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-01-03', 'Sat', '聖誕期平日', '平日', '聖誕期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-01-04', 'Sun', '聖誕期主日', '主日', '聖誕期',true, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-01-05', 'Mon', '聖誕期平日', '平日', '聖誕期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-01-06', 'Tue', '主顯節', '節日', '聖誕期', false,true);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-01-07', 'Wed', '聖誕期平日', '平日', '聖誕期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-01-08', 'Thu', '聖誕期平日', '平日', '聖誕期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-01-09', 'Fri', '聖誕期平日', '平日', '聖誕期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-01-10', 'Sat', '聖誕期平日', '平日', '聖誕期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-01-11', 'Sun', '主受洗日', '慶日', '常年期開始',true,true);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-01-12', 'Mon', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-01-13', 'Tue', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-01-14', 'Wed', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-01-15', 'Thu', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-01-16', 'Fri', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-01-17', 'Sat', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-01-18', 'Sun', '常年期主日', '主日', '常年期',true, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-01-19', 'Mon', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-01-20', 'Tue', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-01-21', 'Wed', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-01-22', 'Thu', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-01-23', 'Fri', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-01-24', 'Sat', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-01-25', 'Sun', '常年期主日', '主日', '常年期',true, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-01-26', 'Mon', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-01-27', 'Tue', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-01-28', 'Wed', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-01-29', 'Thu', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-01-30', 'Fri', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-01-31', 'Sat', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-02-01', 'Sun', '常年期主日', '主日', '常年期',true, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-02-02', 'Mon', '獻主節（聖母行潔淨禮）', '慶日', '常年期', false,true);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-02-03', 'Tue', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-02-04', 'Wed', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-02-05', 'Thu', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-02-06', 'Fri', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-02-07', 'Sat', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-02-08', 'Sun', '常年期主日', '主日', '常年期',true, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-02-09', 'Mon', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-02-10', 'Tue', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-02-11', 'Wed', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-02-12', 'Thu', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-02-13', 'Fri', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-02-14', 'Sat', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-02-15', 'Sun', '常年期主日', '主日', '常年期',true, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-02-16', 'Mon', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-02-17', 'Tue', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-02-18', 'Wed', '聖灰禮儀日（四旬期首日）', '齋期', '四旬期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-02-19', 'Thu', '四旬期平日', '平日', '四旬期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-02-20', 'Fri', '四旬期平日', '平日', '四旬期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-02-21', 'Sat', '四旬期平日', '平日', '四旬期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-02-22', 'Sun', '四旬期主日', '主日', '四旬期',true, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-02-23', 'Mon', '四旬期平日', '平日', '四旬期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-02-24', 'Tue', '四旬期平日', '平日', '四旬期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-02-25', 'Wed', '四旬期平日', '平日', '四旬期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-02-26', 'Thu', '四旬期平日', '平日', '四旬期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-02-27', 'Fri', '四旬期平日', '平日', '四旬期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-02-28', 'Sat', '四旬期平日', '平日', '四旬期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-03-01', 'Sun', '四旬期主日', '主日', '四旬期',true, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-03-02', 'Mon', '四旬期平日', '平日', '四旬期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-03-03', 'Tue', '四旬期平日', '平日', '四旬期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-03-04', 'Wed', '四旬期平日', '平日', '四旬期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-03-05', 'Thu', '四旬期平日', '平日', '四旬期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-03-06', 'Fri', '四旬期平日', '平日', '四旬期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-03-07', 'Sat', '四旬期平日', '平日', '四旬期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-03-08', 'Sun', '四旬期主日', '主日', '四旬期',true, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-03-09', 'Mon', '四旬期平日', '平日', '四旬期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-03-10', 'Tue', '四旬期平日', '平日', '四旬期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-03-11', 'Wed', '四旬期平日', '平日', '四旬期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-03-12', 'Thu', '四旬期平日', '平日', '四旬期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-03-13', 'Fri', '四旬期平日', '平日', '四旬期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-03-14', 'Sat', '四旬期平日', '平日', '四旬期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-03-15', 'Sun', '四旬期主日', '主日', '四旬期',true, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-03-16', 'Mon', '四旬期平日', '平日', '四旬期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-03-17', 'Tue', '四旬期平日', '平日', '四旬期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-03-18', 'Wed', '四旬期平日', '平日', '四旬期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-03-19', 'Thu', '聖若瑟節', '節日', '四旬期', false,true);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-03-20', 'Fri', '四旬期平日', '平日', '四旬期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-03-21', 'Sat', '四旬期平日', '平日', '四旬期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-03-22', 'Sun', '四旬期主日', '主日', '四旬期',true, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-03-23', 'Mon', '四旬期平日', '平日', '四旬期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-03-24', 'Tue', '四旬期平日', '平日', '四旬期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-03-25', 'Wed', '聖母領報', '節日', '四旬期', false,true);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-03-26', 'Thu', '四旬期平日', '平日', '四旬期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-03-27', 'Fri', '四旬期平日', '平日', '四旬期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-03-28', 'Sat', '四旬期平日', '平日', '四旬期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-03-29', 'Sun', '聖枝主日（苦難主日）', '節日', '聖週',true,true);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-03-30', 'Mon', '四旬期平日', '平日', '四旬期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-03-31', 'Tue', '四旬期平日', '平日', '四旬期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-04-01', 'Wed', '四旬期平日', '平日', '四旬期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-04-02', 'Thu', '聖週四（主的晚餐）', '節日', '逾越節三日慶', false,true);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-04-03', 'Fri', '聖週五（主受難日）', '節日', '逾越節三日慶', false,true);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-04-04', 'Sat', '聖週六（復活前夕守夜禮）', '節日', '逾越節三日慶', false,true);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-04-05', 'Sun', '復活主日', '節日', '復活期',true,true);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-04-06', 'Mon', '復活期平日', '平日', '復活期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-04-07', 'Tue', '復活期平日', '平日', '復活期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-04-08', 'Wed', '復活期平日', '平日', '復活期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-04-09', 'Thu', '復活期平日', '平日', '復活期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-04-10', 'Fri', '復活期平日', '平日', '復活期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-04-11', 'Sat', '復活期平日', '平日', '復活期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-04-12', 'Sun', '復活期主日', '主日', '復活期',true, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-04-13', 'Mon', '復活期平日', '平日', '復活期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-04-14', 'Tue', '復活期平日', '平日', '復活期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-04-15', 'Wed', '復活期平日', '平日', '復活期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-04-16', 'Thu', '復活期平日', '平日', '復活期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-04-17', 'Fri', '復活期平日', '平日', '復活期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-04-18', 'Sat', '復活期平日', '平日', '復活期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-04-19', 'Sun', '復活期主日', '主日', '復活期',true, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-04-20', 'Mon', '復活期平日', '平日', '復活期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-04-21', 'Tue', '復活期平日', '平日', '復活期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-04-22', 'Wed', '復活期平日', '平日', '復活期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-04-23', 'Thu', '復活期平日', '平日', '復活期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-04-24', 'Fri', '復活期平日', '平日', '復活期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-04-25', 'Sat', '復活期平日', '平日', '復活期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-04-26', 'Sun', '復活期主日', '主日', '復活期',true, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-04-27', 'Mon', '復活期平日', '平日', '復活期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-04-28', 'Tue', '復活期平日', '平日', '復活期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-04-29', 'Wed', '復活期平日', '平日', '復活期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-04-30', 'Thu', '復活期平日', '平日', '復活期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-05-01', 'Fri', '復活期平日', '平日', '復活期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-05-02', 'Sat', '復活期平日', '平日', '復活期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-05-03', 'Sun', '復活期主日', '主日', '復活期',true, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-05-04', 'Mon', '復活期平日', '平日', '復活期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-05-05', 'Tue', '復活期平日', '平日', '復活期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-05-06', 'Wed', '復活期平日', '平日', '復活期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-05-07', 'Thu', '復活期平日', '平日', '復活期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-05-08', 'Fri', '復活期平日', '平日', '復活期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-05-09', 'Sat', '復活期平日', '平日', '復活期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-05-10', 'Sun', '復活期主日', '主日', '復活期',true, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-05-11', 'Mon', '復活期平日', '平日', '復活期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-05-12', 'Tue', '復活期平日', '平日', '復活期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-05-13', 'Wed', '復活期平日', '平日', '復活期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-05-14', 'Thu', '耶穌升天節', '節日', '復活期', false,true);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-05-15', 'Fri', '復活期平日', '平日', '復活期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-05-16', 'Sat', '復活期平日', '平日', '復活期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-05-17', 'Sun', '復活期主日', '主日', '復活期',true, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-05-18', 'Mon', '復活期平日', '平日', '復活期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-05-19', 'Tue', '復活期平日', '平日', '復活期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-05-20', 'Wed', '復活期平日', '平日', '復活期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-05-21', 'Thu', '復活期平日', '平日', '復活期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-05-22', 'Fri', '復活期平日', '平日', '復活期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-05-23', 'Sat', '復活期平日', '平日', '復活期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-05-24', 'Sun', '聖神降臨節', '節日', '復活期',true,true);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-05-25', 'Mon', '復活期平日', '平日', '復活期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-05-26', 'Tue', '復活期平日', '平日', '復活期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-05-27', 'Wed', '復活期平日', '平日', '復活期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-05-28', 'Thu', '復活期平日', '平日', '復活期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-05-29', 'Fri', '復活期平日', '平日', '復活期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-05-30', 'Sat', '復活期平日', '平日', '復活期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-05-31', 'Sun', '天主聖三節', '節日', '常年期',true,true);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-06-01', 'Mon', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-06-02', 'Tue', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-06-03', 'Wed', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-06-04', 'Thu', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-06-05', 'Fri', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-06-06', 'Sat', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-06-07', 'Sun', '基督聖體聖血節', '節日', '常年期',true,true);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-06-08', 'Mon', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-06-09', 'Tue', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-06-10', 'Wed', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-06-11', 'Thu', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-06-12', 'Fri', '耶穌聖心節', '節日', '常年期', false,true);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-06-13', 'Sat', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-06-14', 'Sun', '常年期主日', '主日', '常年期',true, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-06-15', 'Mon', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-06-16', 'Tue', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-06-17', 'Wed', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-06-18', 'Thu', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-06-19', 'Fri', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-06-20', 'Sat', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-06-21', 'Sun', '常年期主日', '主日', '常年期',true, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-06-22', 'Mon', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-06-23', 'Tue', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-06-24', 'Wed', '聖若翰洗者誕辰', '節日', '常年期', false,true);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-06-25', 'Thu', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-06-26', 'Fri', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-06-27', 'Sat', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-06-28', 'Sun', '常年期主日', '主日', '常年期',true, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-06-29', 'Mon', '聖伯多祿及聖保祿宗徒', '節日', '常年期', false,true);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-06-30', 'Tue', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-07-01', 'Wed', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-07-02', 'Thu', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-07-03', 'Fri', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-07-04', 'Sat', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-07-05', 'Sun', '常年期主日', '主日', '常年期',true, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-07-06', 'Mon', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-07-07', 'Tue', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-07-08', 'Wed', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-07-09', 'Thu', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-07-10', 'Fri', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-07-11', 'Sat', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-07-12', 'Sun', '常年期主日', '主日', '常年期',true, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-07-13', 'Mon', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-07-14', 'Tue', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-07-15', 'Wed', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-07-16', 'Thu', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-07-17', 'Fri', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-07-18', 'Sat', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-07-19', 'Sun', '常年期主日', '主日', '常年期',true, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-07-20', 'Mon', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-07-21', 'Tue', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-07-22', 'Wed', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-07-23', 'Thu', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-07-24', 'Fri', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-07-25', 'Sat', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-07-26', 'Sun', '常年期主日', '主日', '常年期',true, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-07-27', 'Mon', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-07-28', 'Tue', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-07-29', 'Wed', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-07-30', 'Thu', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-07-31', 'Fri', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-08-01', 'Sat', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-08-02', 'Sun', '常年期主日', '主日', '常年期',true, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-08-03', 'Mon', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-08-04', 'Tue', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-08-05', 'Wed', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-08-06', 'Thu', '耶穌顯聖容', '慶日', '常年期', false,true);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-08-07', 'Fri', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-08-08', 'Sat', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-08-09', 'Sun', '常年期主日', '主日', '常年期',true, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-08-10', 'Mon', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-08-11', 'Tue', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-08-12', 'Wed', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-08-13', 'Thu', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-08-14', 'Fri', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-08-15', 'Sat', '聖母蒙召升天', '節日', '常年期', false,true);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-08-16', 'Sun', '常年期主日', '主日', '常年期',true, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-08-17', 'Mon', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-08-18', 'Tue', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-08-19', 'Wed', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-08-20', 'Thu', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-08-21', 'Fri', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-08-22', 'Sat', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-08-23', 'Sun', '常年期主日', '主日', '常年期',true, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-08-24', 'Mon', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-08-25', 'Tue', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-08-26', 'Wed', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-08-27', 'Thu', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-08-28', 'Fri', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-08-29', 'Sat', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-08-30', 'Sun', '常年期主日', '主日', '常年期',true, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-08-31', 'Mon', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-09-01', 'Tue', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-09-02', 'Wed', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-09-03', 'Thu', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-09-04', 'Fri', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-09-05', 'Sat', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-09-06', 'Sun', '常年期主日', '主日', '常年期',true, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-09-07', 'Mon', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-09-08', 'Tue', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-09-09', 'Wed', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-09-10', 'Thu', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-09-11', 'Fri', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-09-12', 'Sat', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-09-13', 'Sun', '常年期主日', '主日', '常年期',true, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-09-14', 'Mon', '光榮十字聖架', '慶日', '常年期', false,true);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-09-15', 'Tue', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-09-16', 'Wed', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-09-17', 'Thu', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-09-18', 'Fri', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-09-19', 'Sat', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-09-20', 'Sun', '常年期主日', '主日', '常年期',true, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-09-21', 'Mon', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-09-22', 'Tue', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-09-23', 'Wed', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-09-24', 'Thu', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-09-25', 'Fri', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-09-26', 'Sat', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-09-27', 'Sun', '常年期主日', '主日', '常年期',true, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-09-28', 'Mon', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-09-29', 'Tue', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-09-30', 'Wed', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-10-01', 'Thu', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-10-02', 'Fri', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-10-03', 'Sat', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-10-04', 'Sun', '常年期主日', '主日', '常年期',true, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-10-05', 'Mon', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-10-06', 'Tue', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-10-07', 'Wed', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-10-08', 'Thu', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-10-09', 'Fri', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-10-10', 'Sat', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-10-11', 'Sun', '常年期主日', '主日', '常年期',true, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-10-12', 'Mon', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-10-13', 'Tue', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-10-14', 'Wed', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-10-15', 'Thu', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-10-16', 'Fri', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-10-17', 'Sat', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-10-18', 'Sun', '常年期主日', '主日', '常年期',true, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-10-19', 'Mon', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-10-20', 'Tue', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-10-21', 'Wed', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-10-22', 'Thu', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-10-23', 'Fri', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-10-24', 'Sat', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-10-25', 'Sun', '常年期主日', '主日', '常年期',true, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-10-26', 'Mon', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-10-27', 'Tue', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-10-28', 'Wed', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-10-29', 'Thu', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-10-30', 'Fri', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-10-31', 'Sat', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-11-01', 'Sun', '諸聖節', '節日', '常年期',true,true);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-11-02', 'Mon', '追思已亡諸信者', '紀念', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-11-03', 'Tue', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-11-04', 'Wed', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-11-05', 'Thu', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-11-06', 'Fri', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-11-07', 'Sat', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-11-08', 'Sun', '常年期主日', '主日', '常年期',true, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-11-09', 'Mon', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-11-10', 'Tue', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-11-11', 'Wed', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-11-12', 'Thu', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-11-13', 'Fri', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-11-14', 'Sat', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-11-15', 'Sun', '常年期主日', '主日', '常年期',true, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-11-16', 'Mon', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-11-17', 'Tue', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-11-18', 'Wed', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-11-19', 'Thu', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-11-20', 'Fri', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-11-21', 'Sat', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-11-22', 'Sun', '常年期主日', '主日', '常年期',true, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-11-23', 'Mon', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-11-24', 'Tue', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-11-25', 'Wed', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-11-26', 'Thu', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-11-27', 'Fri', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-11-28', 'Sat', '常年期平日', '平日', '常年期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-11-29', 'Sun', '將臨期第一主日', '主日', '將臨期',true, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-11-30', 'Mon', '將臨期平日', '平日', '將臨期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-12-01', 'Tue', '將臨期平日', '平日', '將臨期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-12-02', 'Wed', '將臨期平日', '平日', '將臨期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-12-03', 'Thu', '將臨期平日', '平日', '將臨期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-12-04', 'Fri', '將臨期平日', '平日', '將臨期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-12-05', 'Sat', '將臨期平日', '平日', '將臨期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-12-06', 'Sun', '將臨期主日', '主日', '將臨期',true, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-12-07', 'Mon', '將臨期平日', '平日', '將臨期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-12-08', 'Tue', '聖母始胎無染原罪', '節日', '將臨期', false,true);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-12-09', 'Wed', '將臨期平日', '平日', '將臨期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-12-10', 'Thu', '將臨期平日', '平日', '將臨期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-12-11', 'Fri', '將臨期平日', '平日', '將臨期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-12-12', 'Sat', '將臨期平日', '平日', '將臨期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-12-13', 'Sun', '將臨期主日', '主日', '將臨期',true, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-12-14', 'Mon', '將臨期平日', '平日', '將臨期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-12-15', 'Tue', '將臨期平日', '平日', '將臨期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-12-16', 'Wed', '將臨期平日', '平日', '將臨期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-12-17', 'Thu', '將臨期平日', '平日', '將臨期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-12-18', 'Fri', '將臨期平日', '平日', '將臨期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-12-19', 'Sat', '將臨期平日', '平日', '將臨期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-12-20', 'Sun', '將臨期主日', '主日', '將臨期',true, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-12-21', 'Mon', '將臨期平日', '平日', '將臨期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-12-22', 'Tue', '將臨期平日', '平日', '將臨期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-12-23', 'Wed', '將臨期平日', '平日', '將臨期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-12-24', 'Thu', '將臨期平日', '平日', '將臨期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-12-25', 'Fri', '耶穌聖誕節', '節日', '聖誕期', false,true);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-12-26', 'Sat', '聖誕期平日', '平日', '聖誕期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-12-27', 'Sun', '聖若望宗徒聖史', '慶日', '聖誕期',true,true);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-12-28', 'Mon', '諸聖嬰孩殉道', '慶日', '聖誕期', false,true);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-12-29', 'Tue', '聖誕期平日', '平日', '聖誕期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-12-30', 'Wed', '聖誕期平日', '平日', '聖誕期', false, false);
INSERT INTO liturgical_calendar (date, weekday, celebration, liturgical_rank, season, is_sunday, is_holy_day) 
VALUES ('2026-12-31', 'Thu', '聖誕期平日', '平日', '聖誕期', false, false);

-- https://gcatholic.org/calendar/2026/General-A-zt